GEOor/GEOor

src/main/resources/templates/WMS.html
- WFS Layer 생성 및 색상 변경 코드는 삭제하였습니다. (Geosever에서 WMS style 변경)
- WMS Layer 호출 및 생성하는 코드 추가
=> feat: get WMS Layer

src/main/java/geo/hs/HsApplication.java, src/main/java/geo/hs/crawling/Crawler.java, src/main/java/geo/hs/model/dsm/Dsm.java, src/main/java/geo/hs/model/scheduler/SchedulerSunInfo.java, src/main/java/geo/hs/repository/GetDsmRepository.java, src/main/java/geo/hs/repository/JdbcTemplateMJ.java, src/main/java/geo/hs/scheduler/Scheduler.java, src/main/java/geo/hs/service/ShpService.java, src/main/resources/application.properties
- scheduling을 어떻게 구현할 지는 노션 [링크](https://www.notion.so/12-f541caf58f684a62a4e6f6e040203f1c)에 설명해놓았습니다.
- 현재는 태양 파라미터를 크롤링 하는 부분과 dsm을 db로 부터 가져오는 부분은 개발을 완료하였습니다.
- 이제 가져온 dsm을 hillShade 알고리즘을 돌리고, 해당 부분을 shp 파일과 매칭 시키는 부분의 코드를 작성하면 됩니다.
- 앞의 부분이 완성이 되면 제가 전체적인 테스트를 진행할 예정입니다.
=> feat: sun param and dsm scheduler

src/main/resources/templates/WMS.html
1. 주소를 xy좌표로 변환하는 코드
2. 입력받는 날짜의 범위를 지정하는 코드
3. 입력받은 주소, 날짜, 시간, 옵션의 여부를 가져오는 코드
=> FEAT bring input data

src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/model/DTO/PostHillShadeReq.java, src/main/java/geo/hs/model/dsm/Dsm.java, src/main/java/geo/hs/repository/GetDsmRepository.java, src/main/java/geo/hs/scheduler/Scheduler.java, src/main/java/geo/hs/service/DsmService.java
현재 HillShade값을 실시간으로 갱신하는 api를 개발 중에 있습니다.
로직 개발을 동시에 하기 위해 임시로 pr 날립니다.
=> feat: developing hillShade update api

src/main/java/geo/hs/algorithm/hillshade/HillshadeAlgorithm.java, src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/crawling/Crawler.java, src/main/java/geo/hs/model/dsm/Dsm.java, src/main/java/geo/hs/model/hillshade/Hillshade.java, src/main/java/geo/hs/repository/GetDsmRepository.java, src/main/java/geo/hs/scheduler/Scheduler.java, src/main/java/geo/hs/service/HillShadeService.java
HillShade 계산 이전 과정 구현
- DB에서 DSM 가져오기
- 태양 파라미터 크롤링 실행
- HillShade 수행
뒷 부분은 DSM 격자에 맞춰서 일치하는 polygon을 업데이트 하면 됩니다.
=> feat: develop before calc hillShade

src/main/java/geo/hs/algorithm/hillshade/HillshadeAlgorithm.java, src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/geoUtil/WKB.java, src/main/java/geo/hs/model/hillshade/Hillshade.java, src/main/java/geo/hs/repository/RoadRepository.java, src/main/java/geo/hs/scheduler/Scheduler.java, src/main/java/geo/hs/service/DsmService.java, src/main/java/geo/hs/service/HillShadeService.java, src/main/java/geo/hs/service/RoadService.java, src/main/resources/templates/wms.js
- hillshadeController의 이 부분에 해당하는 코드들을 고쳤습니다.
- 기존에 정해진 규격으로 들어오던 dsm 좌표가 무작위로 들어오기 때문에 그에 맞게 2차원 배열을 만들어 줘야 했습니다. 
- 과정은 다음과 같습니다.
1. 일단 dsm List를 돌면서 나온 x, y 좌표 각각의 값들을 hashmap을 사용해 기록해둡니다.
2. 나왔던 모든 x, y 좌표들을 포함하는 2차원 배열을 만들어 줍니다.
3. 나왔던 모든 x, y 좌표들을 정렬하고, 순차적으로 돌면서 dsm List에 있는 (y, x) 쌍은 추가하고, 없는 (y, x) 쌍은 더미 데이터로 넣습니다.
4. 이전과 동일하게 hillshade algorithm을 사용하되, 더미 데이터가 있는 부분은 따로 처리하지 않습니다.
코드
```
public ArrayList<ArrayList<Dsm>> dsm2DConverter(List<Dsm> dsms) {
// 1. List를 돌면서, 나왔던 x, y 좌표 각각을 기록
//y, x 좌표 하나씩만 들어가게 map 처리
HashMap<String, Integer> mapX = new HashMap<String, Integer>();
HashMap<String, Integer> mapY = new HashMap<String, Integer>();
HashMap<String, Dsm> mapXY = new HashMap<String, Dsm>();
// y, x 좌표 들어갈 리스트
ArrayList<Double> y = new ArrayList<Double>();
ArrayList<Double> …
```
=> hillshade 변환기 수정

build.gradle, hs_err_pid17268.log, src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/crawling/Crawler.java, src/main/java/geo/hs/model/DTO/PostHillShadeReq.java, src/main/java/geo/hs/model/dsm/Dsm.java, src/main/java/geo/hs/repository/GetDsmRepository.java, src/main/java/geo/hs/service/DsmService.java, src/main/resources/application.properties
DSM DB가 있다는 가정하에 테스팅 한 코드입니다. (CityCode 제외)
테스팅 해보고 싶으시면 실행 후 Post Method로 "/test" url 호출하시면 됩니다.
현재 테스트는 HillShade 계산하는 부분까지만 돌려보았습니다.
현재는 HillShade 계산하는 부분에서 Heap 초과가 나고 있습니다.
혹시 Crawler 부분에서 Error 뜨시면 ChromeDriver 버전 맞추시면 돌아갑니다.
=> Testing Code

src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/geoUtil/WKB.java, src/main/java/geo/hs/model/DTO/PostHillShadeReq.java, src/main/java/geo/hs/model/road/Road.java, src/main/java/geo/hs/repository/GetDsmRepository.java, src/main/java/geo/hs/repository/RoadRepository.java, src/main/java/geo/hs/service/DsmService.java, src/main/java/geo/hs/service/RoadService.java
시도 코드는 앞 2자리가 온다고 가정합니다.
ex) 서울의 경우 11로 입력받음
dsm 개수를 생각하면 모든 dsm 정보를 리스트로 받으면 힙 오버플로우가 날 거 같은데
이 부분은 전체 데이터를 넣고 테스트를 해야할 거 같습니다.
=> Test: HillShade test에 db 접근 코드 구현

src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/repository/RoadRepository.java, src/main/java/geo/hs/service/DsmService.java, src/main/java/geo/hs/service/RoadService.java
쿼리를 새로 설계된 디비에 맞췄습니다.
api에선 hillshade 계산이 잘 되는데 front단에선 분기가 제대로 수행되지 않아 wms 출력을 건너뛰는 문제가 있습니다.
=> Test: db 테스트

build.gradle, src/main/java/geo/hs/crawling/Crawler.java
현재 문제점
- chrome 버전에 따라 서로 다른 chromedriver를 사용해야함
해결 방안
- 사용자의 크롬 버전에 맞게 chromedriver를 다운로드하는 오픈소스인 WebDriverManager를 도입
저는 적용해도 문제가 발생하지 않는데 확인 부탁드립니다.
=> WebDriverManager 적용

src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/repository/FrozenRepository.java, src/main/java/geo/hs/service/DsmService.java, src/main/java/geo/hs/service/HillShadeService.java
코드가 valueOf()랑 parse...()를 혼용해서 사용하고 있습니다.
검색해보니 parse...()를 사용하는 것이 더 좋다고 나와있어서 parse...()로 통일했습니다.
=> double 형변환 방법 통일

src/main/java/geo/hs/crawling/Crawler.java
적경을 시분초로 받아서 각도로 변환한 값을 degree 변수를 저장할 수 있도록 추가했습니다.
=> refactor: 변수 이름 명확하게 구분할 수 있도록 변경

src/test/java/geo/hs/service/DsmServiceTest.java
안녕하세요! DsmService의 테스트 코드를 만들었습니다.
JUnit으로 테스트를 진행하려면 아래처럼 설정하면 된다고 합니다.
File → Settings → Build, Execution, Deployment → Gradle → Run tests using → IntelliJ IDEA
=> Add dsmService unit test

src/main/java/geo/hs/crawling/Crawler.java, src/main/resources/templates/WMS.html, src/main/resources/templates/wfs.css, src/main/resources/templates/wms.js
HillShade controller 개선 전 front 코드 리팩토링
=> front 코드 리팩토링

src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/crawling/Crawler.java, src/main/java/geo/hs/model/DTO/PostHillShadeReq.java, src/main/java/geo/hs/repository/GetDsmRepository.java, src/main/java/geo/hs/repository/RoadRepository.java, src/main/java/geo/hs/service/DsmService.java, src/main/java/geo/hs/service/RoadService.java, src/main/resources/application.properties, src/test/java/geo/hs/service/DsmServiceTest.java
시군구 코드 비교하는 과정에서 문자열보다는 숫자가 더 나은거 같아서 int로 바꿨습니다.
주석 중에 hillshade란 표현을 HillShade로 바꾸긴 했는데.. 이 컨벤션을 어떻게 해야할지 의견을 나눠야 할 거 같습니다.
Crawler 코드에서 #28 pr에서 해결한 TODO 주석을 제거하지 않은 거 같아서 제거했습니다.
다들 문제 없다 판단되면 현재 브랜치의 커밋들을 develop 브랜치에 pr 하겠습니다.
다만, 이 pr이 머지되면 db를 다시 세팅해주셔야 합니다.
=> Refact: 시군구 코드 타입을 String->int로 바꿈

src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/crawling/Crawler.java, src/main/java/geo/hs/crawling/crawler.log, src/main/java/geo/hs/model/DTO/BasicDataReq.java, src/main/java/geo/hs/model/DTO/PostHillShadeReq.java, src/main/java/geo/hs/repository/GetDsmRepository.java, src/main/java/geo/hs/repository/HazardRepository.java, src/main/java/geo/hs/repository/RoadRepository.java, src/main/java/geo/hs/service/DsmService.java, src/main/java/geo/hs/service/RoadService.java, src/main/resources/application.properties, src/main/resources/templates/WMS.html, src/main/resources/templates/wfs.css, src/main/resources/templates/wms.js, src/test/java/geo/hs/service/DsmServiceTest.java
필수 기능은 완성이 됐으니 개발 브랜치에 합치고 다시 작업을 이어나가는게 좋다고 생각합니다!
squash merge로 할 거기 때문에 기존 refact-hillshade 브랜치는 지울 것입니다.
이후 리팩토링 작업 pr은 develop 브랜치 아니면 새로운 리팩토링 브랜치에 할지 고민인데... 여기에 대해 어떻게 생각하시는지 궁금합니다.
=> Refact hillshade 작업 중간 정리

src/main/java/geo/hs/crawling/Crawler.java
- Crawler 코드 주석 설명 추가
- Crawler 코드 리팩토링
=> refactor: Crawler 코드 리팩토링

src/main/java/geo/hs/crawling/Crawler.java
Reverts GEOor/GEOor#45
커밋된 코드들이 제대로 반영이 안 돼서 뒤로 돌림
=> Revert "Develop 동기화"

src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/crawling/Crawler.java, src/main/java/geo/hs/crawling/crawler.log, src/main/java/geo/hs/model/DTO/BasicDataReq.java, src/main/java/geo/hs/model/DTO/PostHillShadeReq.java, src/main/java/geo/hs/repository/GetDsmRepository.java, src/main/java/geo/hs/repository/HazardRepository.java, src/main/java/geo/hs/repository/RoadRepository.java, src/main/java/geo/hs/service/DsmService.java, src/main/java/geo/hs/service/RoadService.java, src/main/resources/application.properties, src/main/resources/templates/WMS.html, src/main/resources/templates/wfs.css, src/main/resources/templates/wms.js, src/test/java/geo/hs/service/DsmServiceTest.java
#45 ~ #48 pr에서 파일 변경이 안 된 사항들 수정했습니다.
머지하기 전에 자신이 작업한 내용이 빠진게 있는지 확인해주세요
=> Fix file not change

src/main/java/geo/hs/controller/HazardController.java, src/main/java/geo/hs/controller/HillShadeController.java, src/main/java/geo/hs/crawling/Crawler.java
- Hazard Controller
- HillShadeController
- Crawler
설명이 필요한 부분은 주석을 새로 추가했습니다.
=> 주석 추가 및 수정

src/main/resources/templates/wms.js
=> 마커 zIndex 변경

src/main/java/geo/hs/controller/HillShadeController.java
이전에는 시간만 받아 온 것 같은데, 지금은 분까지 받아와서 데이터가 hh:mm 형식으로 되어 있기 때문에 hh를 integer로 변환하도록 했습니다.
=> fix: 시간 데이터 파싱 수정
